### ISSUE TITLE
can't find app after install

### ISSUE THREAD

**Issue by qzwongo** [veniosg/JustSearch#10]
Running lineageos 15.1 on OnePlus 5t. Installed via fdroid. Fdroid didn't offer option to run after indicating successful install, only to uninstall. App not available on desktop or in drawer. 
Uninstalled and installed via Play Store, same behavior - option to uninstall but not open the app, no app in drawer or desktop.

**Comment by veniosg** [comment]
Hey I know this is confusing and there is #6 to remedy that. Just Search is an assist replacement, the app that launches when holding on the home button. To use it go to settings, search for Assist app, and set Just Search as the default.

**Comment by qzwongo** [comment]
Thanks for the quick response and the education! I see that explanation now in the Play Store app description (though not in the fdroid description).
