### ISSUE TITLE
new logo for just search

### ISSUE THREAD

**Issue by ajihasan** [veniosg/JustSearch#14]
Hai, @veniosg .
I wanted to contribute to just search. I designed a logo for just search. if you like it, I'll send you the files.

![icon just search](https://user-images.githubusercontent.com/36501149/38301086-bb51b192-3828-11e8-98cd-8298cc7217ed.png)

my concept

![konsep just search 300 px](https://user-images.githubusercontent.com/36501149/38301383-92f167d2-3829-11e8-859c-e6e36e624ea8.png)

if you need change, please let me know. I will fix it.

**Comment by veniosg** [comment]
Thanks for your effort but I'm afraid I cannot merge this. This project doesn't need a new icon. If you're going to contribute to other projects may I suggest following the material guidelines, thinking about how the icon might look when scaled down to 48px and discussing with the project maintainers before starting so you don't waste your efforts.
