### ISSUE TITLE
Add a search widget

### ISSUE THREAD

**Issue by pablorosatti** [veniosg/JustSearch#16]
Simply that will be great.

**Comment by ildar** [comment]
There are lots in the wild. Why you'd want another one?

**Comment by pablorosatti** [comment]
I don't have one, i was deleted the Google Search app and actually the only
Search widget dissapeared.

**Comment by pablorosatti** [comment]
But there are no Open Source.

**Comment by ildar** [comment]
Duck Duck Go (DuckDuckGo search provider) -
https://f-droid.org/app/se.johanhil.duckduckgo

**Comment by pablorosatti** [comment]
That Is a browser, not a Simply and clean widget (like the Google Search one)

**Comment by pablorosatti** [comment]
To make Just Search a complete and light weight Google  Search alternative

**Comment by veniosg** [comment]
Ildar, just search is not tied to a specific search engine, and the widget will reflect that. Using another app only for the widget would be a radically worse experience than Just Search being able to expose its own. 
That being said, there is already an issue open for the widget so I'm closing this in favour of #7
