### ISSUE TITLE
[FR] bang (exclamation) search providers

### ISSUE THREAD

**Issue by ildar** [veniosg/JustSearch#18]
E.g. if I search "JustSearch !yt" with DDG, it'll search "JustSearch" in YouTube.
Nice to have JS opening URL directly, skipping a browser, in an app handling YT URLs (NewPipe in my case)
The same with other bang shortcuts: * Maps, etc.

**Comment by veniosg** [comment]
Unfortunately I would consider this undertaking to be outside the scope of the project. 
That being said, I'd expect such redirections to be possible on the browser side, albeit this would open two apps in sequence.
