### ISSUE TITLE
allow to modify urls

### ISSUE THREAD

**Issue by Lockdis** [veniosg/JustSearch#23]
hello it would be very useful to be able to edit the url of engines because you can pass several parameters in the url, thanks. longpress on an engine to edit it would be perfect

**Comment by veniosg** [comment]
Hi Lockdis, thanks for the request. The "Custom" option is my preferred solution for this use case at this point as it optimizes for the common, unmodified usage of the providers by keeping the actions minimal and UI clearer. 
Long press is ok, but I wouldn't want to allow completely custom urls for the static options. Maybe allowing icon customization for "Custom" is broader, easier and would completely cover this too.

**Comment by Lockdis** [comment]
i have managed to add parameters to urls in the source and to compile it, thanks.
