### ISSUE TITLE
Distribute on F-Droid

### ISSUE THREAD

**Issue by ontherunvaro** [veniosg/JustSearch#8]
Hi!

I'm wondering if you have considering distributing this app on [F-Droid](https://f-droid.org/), since it's "proudly open-source" :)

I have some experience with that, and if you approve, I can submit the patch to add your app to the repo myself.

Cheers!

**Comment by veniosg** [comment]
Sure, I think F-droid is a great match for this app. Feel free to go ahead and submit it!

**Comment by veniosg** [comment]
Please let me know once you have and I'll close this issue :)

**Comment by ontherunvaro** [comment]
Actually, now that I'm digging around a bit, I see that the version in Google Play is called "Swiss Army Search" still. I think I shall wait until the 1.0.1 release so that the name is changed to avoid having to change it again afterwards (and send another PR to FDroid).

**Comment by veniosg** [comment]
I just checked and I see it as Just Search on Google Play. Where do you see Swiss Army Search? I was sure I've renamed everything :O

**Comment by ontherunvaro** [comment]
![screenshot_20180321-132900](https://user-images.githubusercontent.com/8677743/37709865-e6da7baa-2d0b-11e8-9cf4-ad9e4521a69b.png)

**Comment by veniosg** [comment]
Oh wow. I'll release an update ASAP, great catch!

**Comment by ontherunvaro** [comment]
I ended up manually setting the name in the F-Droid metadata, and doing the PR anyway. It should be alright as long as you keep the same applicationId, which I guess you intend to.

https://gitlab.com/fdroid/fdroiddata/merge_requests/3023

**Comment by veniosg** [comment]
Thanks! 
FYI I just released 1.0.1, and the name seems fixed (at least on my device). Feel free to update your fdroid pull request :)
