### ISSUE TITLE
Add Qwant

### ISSUE THREAD

**Issue by LumenReaper** [veniosg/JustSearch#9]
Hi,

have just found your application on F-Droid and would like to ask you to add the search engine Qwant. Just use `https://www.qwant.com/?q=%s` as url.

Thank you

**Comment by veniosg** [comment]
Sounds easy enough. Would you be able to provide an icon to use for them? If they have a branding page, or official icon for people to use I should be able to bring it in line with the rest in Just Search.

**Comment by LumenReaper** [comment]
Thank you for your answer. 

I found this page: [Qwant Press](https://about.qwant.com/press/). There you can download a zip with the logo in different file formats (png, svg, jpg ,...).

**Comment by veniosg** [comment]
This should do it, thanks :)

**Comment by gbcreation** [comment]
Hi,

I was about to open a similar issue for StartPage, but don't you think it would be more useful to have an option allowing users to add new search engines at will?

**Comment by veniosg** [comment]
I thought I had an issue open for this already. Opened #11

**Comment by LumenReaper** [comment]
I agreed that there should be an option for custom search engines. But Qwant and Startpage are relatively popular for people who focus on privacy, so I would suggest adding them both.

Especially when there is an activity later on, it doesn't matter how many search engines are available.
